apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:2.319
      ports:
        - containerPort: 8080
        - containerPort: 50000
