apiVersion: v1
kind: Pod
metadata:
  name: maven-pod
  labels:
    app: maven
spec:
  containers:
    - name: maven-container
      image: maven:latest
      command: ["mvn"]
      args: ["--version"]

