---
- name: Install Tomcat and Create User
  hosts: host1

  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/ec2-user/test/file1.txt
        dest: /home/ec2-user
        remote_src: yes
      become: true
      
    # - name: Install Tomcat
    #   become: true  # Run as sudo
    #   package:
    #     name: tomcat  # Use 'tomcat' for Red Hat-based systems
    #     state: present

    # - name: Create a user
    #   user:
    #     name: newuser
    #     password: "{{ 'V@k12345' | password_hash('sha512') }}"
    #     state: present
    #     groups: wheel
    #     create_home: yes
    #   become: yes
