apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-prod-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pre-prod-app
  template:
    metadata:
      labels:
        app: pre-prod-app
    spec:
      containers:
        - name: postgres-container
          image: postgres

