pipeline {
    agent any
    
    stages {
        stage('First') {
            steps {
                echo "this is stage 1"
            }
        }
        
        stage('Second') {
            steps {
                echo "this is stage 2"
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'mvn test'
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //     }
        // }
    }
}
